---
title: "Creation of backend functionality for election coverage"
subtitle: "Extended project description"
author: "Alexander Bauer, Andreas Bender, André Klima"
date: "31.10.2018"
output: pdf_document
---

# Part 1: Database setup for KOALA election analyses

#### Main requirements

    1. Modern database setup with a public API
        a) In the database we want to save ...
        ... the data for multiple elections over time
        ... the published opinion polls by different polling agencies.
            For each election, these polls contain different parties. Also,
            for one election the number of parties can change over time (e.g. if a smaller
            party was formerly subsumized in the 'Others' category and is now
            listed with its individual voter share).
        ... the probabilities for specific events (e.g. that two parties
            jointly obtain a seat majority in parliament or that a smaller party
            gets into parliament). For each election, different events can be in
            the focus and it should be possible to introduce new events to the
            database (if we one day decide to newly calculate probabilities
            for other events).
        ... intermediate results of our analyses. In our KOALA method, based on
            opinion poll data, we simulate the election outcome 50,000 times to
            then define e.g. the probability of two parties having a joint majority
            as the relative frequency of cases in which this event is true.
            We want to save the simulated shares in the database.
        b) API access should be able to differentiate between admin users of
        the database and third parties. Third parties should get read-only access.
        c) The data you get for opinion polls, specific probabilities etc.
        is already in long format (at least most of it). 
        The data format can still be changed. Think
        about an optimal format to store the data in the database.
    1. R package for database access
        a) Easy-to-use R package for using the API-access to the database
        b) Functions to retrieve, edit and write data in the database.
        Functions should have adequate filtering options, e.g. to only work
        with the data of specific polling agencies, specific dates, specific parties etc.
        c) R package should be made available on GitHub with adequate documentation



# Part 2: Automatic scraping tool for election results

see project description